use tpch;
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/nation" overwrite into table nation; 
select * from nation limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/orders" overwrite into table orders; 
select * from orders limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/partsupp" overwrite into table partsupp; 
select * from partsupp limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/part" overwrite into table part; 
select * from part limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/region" overwrite into table region; 
select * from region limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/supplier" overwrite into table supplier; 
select * from supplier limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/lineitem" overwrite into table lineitem; 
select * from lineitem limit 10; 
load data inpath "hdfs://node91:9000/wyh/dataset/tpch/customer" overwrite into table customer; 
select * from customer limit 10;
